spring:
  datasource:
#    url: jdbc:postgresql://localhost:5430/shopPriceDB
    url: jdbc:postgresql://host.docker.internal:5430/shopPriceDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  jpa:
    show-sql: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
  file:
    path: /logs
    name: shop_price.log

server:
  port: 8080

shop-price:
  jewelry-shop:
    address: https://mygracefuljewelry.com/shop
    all-jewelry-url: /api/jewelry/all